name: Build-and-Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    # … Build 步骤保持不变 …

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: jar
          path: build/libs

      - name: Determine release info
        id: info
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}      # v1.2.3 or v1.2.3+mc1.20.1
          MOD_ID="${{ needs.build.outputs.mod_id }}"
          # 你也可拆分 TAG_NAME 提取子串，此处直接用全称
          NAME="${MOD_ID} ${TAG_NAME}"
          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "name=$NAME"     >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag:   ${{ steps.info.outputs.tag }}
          name:  ${{ steps.info.outputs.name }}
          files: build/libs/*.jar
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
